# Generated by Django 5.1.1 on 2024-11-11 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_service', '0002_vendorapirequest_remove_pick_buyers_with_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpick',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
