# Generated by Django 5.1.1 on 2024-11-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='meta_data',
            new_name='stats',
        ),
    ]
