# Generated by Django 5.1.1 on 2024-11-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_rename_meta_data_buyer_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
