# Generated by Django 5.1.1 on 2024-11-13 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyer', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=255, unique=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('delta', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Vendor API Request',
                'verbose_name_plural': 'Vendor API Requests',
                'ordering': ['-request_time'],
            },
        ),
        migrations.CreateModel(
            name='ActivePick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('event_start', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('buyers_with_access', models.ManyToManyField(blank=True, related_name='active_picks_buyer_access', to='buyer.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pick_seller', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPick',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('posted_at', models.DateTimeField()),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('event_time_done', models.DateTimeField(auto_now_add=True)),
                ('event_result', models.JSONField(null=True)),
                ('buyers_with_access', models.ManyToManyField(blank=True, related_name='historical_pick_buyer', to='buyer.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_pick_seller', to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('subscribed_until', models.DateTimeField()),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='buyer.buyer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='seller.seller')),
            ],
        ),
    ]
