# Generated by Django 5.1.1 on 2024-12-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepick',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalpick',
            name='did_seller_succeed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpick',
            name='probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='historicalpick',
            name='units_won',
            field=models.IntegerField(default=0),
        ),
    ]
