# Generated by Django 5.1.1 on 2024-11-14 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepick',
            old_name='meta_data',
            new_name='event_data',
        ),
    ]
