# Generated by Django 5.1.1 on 2024-11-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepick',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
