# Generated by Django 5.1.1 on 2024-11-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('league', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('type_of_pick', models.CharField(blank=True, max_length=50, null=True)),
                ('delta', models.IntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Vendor API Request',
                'verbose_name_plural': 'Vendor API Requests',
                'ordering': ['-request_time'],
            },
        ),
        migrations.DeleteModel(
            name='VendorApiRequest',
        ),
    ]
