# Generated by Django 5.1.1 on 2024-11-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_meta_data_activepick_event_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activepick',
            old_name='event_data',
            new_name='pick_data',
        ),
    ]
