# Generated by Django 5.1.1 on 2024-12-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_activepick_probability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apirequest',
            old_name='sport',
            new_name='sport_league',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='league',
        ),
        migrations.RemoveField(
            model_name='apirequest',
            name='type_of_pick',
        ),
    ]
