# Generated by Django 5.1.1 on 2024-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_activepick_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepick',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
