# Generated by Django 5.1.1 on 2024-11-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_apirequest_delete_vendorapirequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='league',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='response_data',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='type_of_pick',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
