# Generated by Django 5.1.1 on 2024-12-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_sport_apirequest_sport_league_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepick',
            name='sport_league',
            field=models.CharField(default='basketball_nba', max_length=100),
            preserve_default=False,
        ),
    ]
