# Generated by Django 5.1.1 on 2024-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_event_data_activepick_pick_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepick',
            name='game_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
