# Generated by Django 5.1.1 on 2024-12-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_activepick_sport_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='type_of_pick',
            field=models.CharField(default='h2h', max_length=100),
            preserve_default=False,
        ),
    ]
