# Generated by Django 5.1.1 on 2024-11-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_activepick_game_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepick',
            name='game_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
