# Generated by Django 5.1.1 on 2024-12-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_apirequest_type_of_pick_verbal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activepick',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
