# Generated by Django 5.1.1 on 2024-12-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_activepick_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpick',
            name='probability',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
