# Generated by Django 5.1.1 on 2024-12-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_historicalpick_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activepick',
            name='buyers_with_access',
        ),
    ]
