# Generated by Django 5.1.1 on 2024-12-18 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_activepick_buyers_with_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpick',
            name='buyers_with_access',
        ),
    ]
