# Generated by Django 5.1.1 on 2024-12-04 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='stats',
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stat_name', models.CharField(max_length=255)),
                ('stat_value', models.IntegerField()),
                ('time_period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='seller.seller')),
            ],
        ),
    ]
