# Generated by Django 5.1.1 on 2024-12-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_seller_stats_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='stat_verbal',
            field=models.CharField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stat',
            name='stat_value',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
