# Generated by Django 5.1.1 on 2024-12-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_alter_stat_stat_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
