# Generated by Django 5.1.1 on 2024-12-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_seller_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='user_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
