# Generated by Django 5.1.1 on 2024-12-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_seller_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
