# Generated by Django 5.1.1 on 2024-12-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_delete_stat'),
        ('seller', '0007_seller_bio'),
    ]

    operations = [
    ]
